# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 腾讯股票

on:
  workflow_dispatch:
  schedule:
    - cron: '10 7 * * *'
  # watch:
  #   types: started
  repository_dispatch:
    types: jd_dreamFactory
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/CenBoMin/GithubSync.git ~/scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: '运行 【腾讯股票】'
        run: | 
          cd ~/scripts
          npm install 
          node TXSTOCK/txstockqx.js
        env:
          https://github.com/CenBoMin/GithubSync.git
          USERHEADER: ${{ secrets.USERHEADER }}
          USERKEY: ${{ secrets.USERKEY }}
          CASHHEADER: ${{ secrets.CASHHEADER }}
          SINGHEADER: ${{ secrets.SINGHEADER }}
          SINGKEY: ${{ secrets.SINGKEY }}
          TASKHEADER: ${{ secrets.TASKHEADER }}
          TASKKEY: ${{ secrets.TASKKEY }}
          WXTASKKEY: ${{ secrets.WXTASKKEY }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          JD_818_SHAREID_NOTIFY: ${{ secrets.JD_818_SHAREID_NOTIFY }}
