name: 腾讯自选股

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */24 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【腾讯自选股】"
              run: |
                  node txstockqx.js
              env:
                  userheader: ${{ secrets.userheaderVal }}
                  userkey: ${{ secrets.userkeyVal }}
                  signheader: ${{ secrets.signheaderVal }}
                  signkey: ${{ secrets.signkeyVal }}
                  taskheader: ${{ secrets.taskheaderVal }}
                  taskkey: ${{ secrets.taskkeyVal }}
                  wxtaskkey: ${{ secrets.wxtaskkeyVal }}
