
name: 羊毛赚




on:

  workflow_dispatch:

  schedule:

     - cron: '0 8,12 * * *'

  watch:

    types: started

jobs:

  build:

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    env:

        YMZ_ymzhuanggBODY: ${{ secrets.YMZ_ymzhuanggBODY }}

        YMZ_ymzhuanspBODY: ${{ secrets.YMZ_ymzhuanspBODY }}

        YMZ_ymzhuantxBODY: ${{ secrets.YMZ_ymzhuantxBODY }}

        ymzhuanUSERID: ${{ secrets.ymzhuanUSERID }}

        YMZ_CASH: ${{ secrets.YMZ_CASH }}

    steps:

      - name: Checkout

        run: |
          git clone https://github.com/ziye11/JavaScript.git ~/JavaScript
      - name: Use Node.js 12.x

        uses: actions/setup-node@v1

        with:

          node-version: 12.x

      - name: npm install

        if: env.ymzhuanUSERID

        run: |
          cd ~/JavaScript
          npm install
      - name: '运行 【羊毛赚】'
        
        if: env.ymzhuanUSERID
       
        run: |
          cd ~/JavaScript
          node Task/ymzhuan.js
        env:

          

          PUSH_KEY: ${{ secrets.PUSH_KEY }}

          BARK_PUSH: ${{ secrets.BARK_PUSH }}

          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}

          TG_USER_ID: ${{ secrets.TG_USER_ID }}

          BARK_SOUND: ${{ secrets.BARK_SOUND }}

          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}

          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
